-- +goose Up
-- +goose StatementBegin
ALTER TABLE public.comments
ALTER COLUMN author
SET DEFAULT '(deleted)';
ALTER TABLE public.articles
ALTER COLUMN author
SET DEFAULT '(deleted)';
ALTER TABLE public.drafts
ALTER COLUMN author
SET DEFAULT '(deleted)';
ALTER TABLE public.files
ALTER COLUMN author
SET DEFAULT '(deleted)';
ALTER TABLE public.threads
ALTER COLUMN author
SET DEFAULT '(deleted)';
-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
ALTER TABLE public.comments
ALTER COLUMN author
SET DEFAULT '[deleted]';
ALTER TABLE public.articles
ALTER COLUMN author
SET DEFAULT '[deleted]';
ALTER TABLE public.drafts
ALTER COLUMN author
SET DEFAULT '[deleted]';
ALTER TABLE public.files
ALTER COLUMN author
SET DEFAULT '[deleted]';
ALTER TABLE public.threads
ALTER COLUMN author
SET DEFAULT '[deleted]';
-- +goose StatementEnd